export const TIP = {
  // tryLatter: '下注校验未通过, 请稍后再试',
  // search: '搜索',
  // commingSoon: '敬请期待',
  // betBanner: '报注信息',
  // countDownStart: 'STARTS IN',
  // sentT: '交易发送上链，请等待',
  // successT: '上链成功',
  // failT: '交易失败',
  // preCheck: '下注预校验未通过, 请稍后再试',
  // betFirst: '请先下注',
  // joinFirst: '请先加入房间',
  // amountMax: '金额不能超过',
  // amountMin: '金额不能小于',
  // createSuccess: '创建成功',
  // authSuccess: '授权成功',
  // roomNumberPlaceholder: '请输入房间号(8位数字)',
  // roomNumberTip: '房间号格式为8位数字',
  // stopBet: '成功停止投注',
  // greaterThen0: '投注金额需要大于0',

  tryLatter: 'Bet verification failed, please try again later',
  search: 'search',
  commingSoon: 'Coming Soon',
  betBanner: 'Bet Info',
  countDownStart: 'STARTS IN',
  sentT: 'Your transaction is being confirmed, please wait',
  successT: 'Storing (data) on blockchain successfully',
  failT: 'Transaction failed',
  preCheck: 'Bet pre-check failed. Please try again later',
  betFirst: 'Please place a bet',
  joinFirst: 'Please join the room first',
  amountMax: 'The amount cannot exceed ',
  amountMin: 'The amount cannot be less than ',
  createSuccess: 'Creation success',
  authSuccess: 'Authorization success',
  roomNumberPlaceholder: 'Please enter room number', // (8 digits)
  roomNumberTip: 'The room number is an 8-digit number',
  stopBet: 'Stop successfully',
  greaterThen0: 'The bet has to be greater than 0',
}