export const TIP = {
  tryLatter: '下注校验未通过, 请稍后再试',
  search: '搜索',
  commingSoon: '敬请期待',
  betBanner: '报注信息',
  countDownStart: '开始倒数',
  sentT: '交易发送上链，请等待',
  successT: '上链成功',
  failT: '交易失败',
  preCheck: '下注预校验未通过, 请稍后再试',
  betFirst: '请先下注',
  joinFirst: '请先加入房间',
  amountMax: '金额不能超过',
  amountMin: '金额不能小于',
  createSuccess: '创建成功',
  authSuccess: '授权成功',
  roomNumberPlaceholder: '请输入房间号(8位数字)',
  roomNumberTip: '房间号格式为8位数字',
  stopBet: '成功停止投注',
  greaterThen0: '投注金额需要大于0',
}